---
name: Linting / Unit Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies with NPM
        id: installation
        run: |
          npm ci
      - name: Run Tests
        id: test
        run: |
           npx turbo run test