---
name: Linting / Unit Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Dependencies with NPM
        id: installation
        working-directory: convert
        run: |
          npm ci
      - name: Run Tests
        id: testing
        working-directory: convert
        run: |
          npm run test